  head_lidar_controller:
    type: effort_controllers/JointVelocityController
    joint: head_lidar_spinning_joint
    pid: {p: 0.4, i: 0.0, d: 0.0}
 
 # head_lidar_controller:
 #   type: velocity_controllers/JointVelocityController
 #   joint: head_lidar_spinning_joint
 #   pid: {p: 100.0, i: 0.01, d: 10.0}
 # head_lidar_controller:
 #   type: effort_controllers/JointVelocityController
 #   joints: 
  #    - head_lidar_spinning_joint
 
 #   gains:
 #      head_lidar_spinning_joint: {p: 100.0, i: 0.01, d: 10.0}